# Generated by Django 3.1.7 on 2021-04-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='next_of_kin_contact_no',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='age',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='country',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='next_of_kin_contact_no',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.doctor'),
        ),
    ]
