# Generated by Django 3.1.7 on 2021-04-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210424_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='otherstaff',
            name='user_type',
        ),
        migrations.AddField(
            model_name='doctor',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
