# Generated by Django 3.1.7 on 2021-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210424_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(to='staff.Speciality'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='specialty',
            field=models.ManyToManyField(to='staff.Speciality'),
        ),
        migrations.AddField(
            model_name='otherstaff',
            name='specialty',
            field=models.ManyToManyField(to='staff.Speciality'),
        ),
    ]
