# Generated by Django 3.1.7 on 2021-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210424_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'External_Doctor'), (3, 'Nurse'), (4, 'Internal_Doctor'), (5, 'Lab_Officer'), (6, 'Small-Admin')], default=1),
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
