# Generated by Django 3.1.7 on 2021-02-25 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_patient',
            name='date_of_adm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='out_patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
