# Generated by Django 3.1.7 on 2021-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20210225_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_no',
            field=models.CharField(default=100, editable=False, max_length=25),
        ),
    ]
