# Generated by Django 3.1.7 on 2021-03-14 15:15

from django.db import migrations, models
import reception.models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_patient_patient_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_no',
            field=models.CharField(default=reception.models.increment_patient_number, editable=False, max_length=25),
        ),
    ]
