# Generated by Django 3.1.7 on 2021-02-25 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='absorved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='inactivated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='live',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='oral',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccineapplied',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
