# Generated by Django 3.1.7 on 2021-03-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210312_1053'),
        ('operations', '0002_auto_20210225_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.diagnose'),
        ),
        migrations.DeleteModel(
            name='Diagnose',
        ),
    ]
