# Generated by Django 3.1.7 on 2021-03-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210312_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='mame',
            new_name='name',
        ),
    ]
