# Generated by Django 3.1.7 on 2021-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210331_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
