# Generated by Django 3.1.7 on 2021-03-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210225_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('S', 'Single Ward'), ('D', 'Double Ward'), ('C', 'Central Ward')], max_length=100),
        ),
    ]
